[@ui.bambooSection titleKey="section.asoc"]
	[@ww.textfield labelKey="label.api.keyid" name="apiKey" descriptionKey="desc.api.keyId" required="true"/]
	[@ww.password labelKey="label.api.secret" name="apiSecret" descriptionKey="desc.api.secret" showPassword="true" required="true"/]
	[@ww.textfield labelKey="label.appid" name="appId"  descriptionKey="desc.appid" required="true"/]
	[@ww.textfield labelKey="label.scanName" name="scanName" descriptionKey="desc.scanName"/]
	[@ww.select labelKey="label.test.type" name="selectedTestType" descriptionKey="desc.testType" required="true" list="testTypeList" toggle="true"/]
	[@ui.bambooSection dependsOn="selectedTestType" showOn="DynamicAnalyzer"]
		[@ww.textfield labelKey="label.target" name="target" descriptionKey="desc.target" required="true"/]
		[@ww.select labelKey="dyn.label.scan.type" name="ScanType" descriptionKey="desc.dynScanType" list="scanTypeList"/]
		[@ww.radio labelKey="dyn.label.test.optimization" name="TestOptimizationLevel" descriptionKey="desc.dyn.testOptimization" list="testOptimizationList" toggle="true"/]
		[@ww.textfield labelKey="dyn.label.login.user" name="LoginUser" descriptionKey="desc.dynLoginUser"/]
		[@ww.password labelKey="dyn.label.login.password" name="LoginPassword" descriptionKey="desc.dynLoginPassword" showPassword="true"/]
		[@ww.textfield labelKey="dyn.label.third.credential" name="extraField" descriptionKey="dyn.thirdCred"/]
		[@ww.textfield labelKey="dyn.label.presence" name="PresenceId" descriptionKey="desc.dynPresence"/]
		[@ww.textfield labelKey="dyn.label.scan.file" name="ScanFile" descriptionKey="desc.dynScanFile"/]
	[/@ui.bambooSection]
	[@ui.bambooSection dependsOn="selectedTestType" showOn="StaticAnalyzer"]
		[@ww.checkbox labelKey="label.open.source.only" name="openSourceOnly" descriptionKey="desc.openSourceOnly" toggle="true"/]
		[@ww.checkbox labelKey="section.scan.speed" name="staticScanSpeedConf" descriptionKey="dec.scanSpeed" toggle="true"/]
		[@ui.bambooSection titleKey="" descriptionKey="" dependsOn="staticScanSpeedConf" showOn="true"]
			[@ww.radio name="staticScanSpeed" labelKey="" list="staticScanSpeedList" toggle="true"/]
		[/@ui.bambooSection]
	[/@ui.bambooSection]
	[@ww.checkbox labelKey="label.email.notification" name="emailNotification" descriptionKey="desc.emailNotification" toggle="true"/]
	[@ww.checkbox labelKey="label.suspend" name="suspendJob" descriptionKey="desc.suspend" toggle="true"/]
[/@ui.bambooSection]

[@ui.bambooSection titleKey="" descriptionKey="" dependsOn="suspendJob" showOn="true"]
	[@ww.checkbox labelKey="section.fail.configure" name="failBuildConfigure" descriptionKey="desc.failConfigure" toggle="true"/]
	[@ui.bambooSection titleKey="" descriptionKey="" dependsOn="failBuildConfigure" showOn="true"]
		[@ww.radio name="selectedFailBuild" labelKey="section.fail" list="failBuildList" toggle="true"/]
		[@ui.bambooSection titleKey="" descriptionKey="desc.section.fail" dependsOn="selectedFailBuild" showOn="failBuildSeverityLevel"]
			[@ww.textfield labelKey="label.total" name="maxTotal"/]
			[@ww.textfield labelKey="label.high" name="maxHigh"/]
			[@ww.textfield labelKey="label.medium" name="maxMedium"/]
			[@ww.textfield labelKey="label.low" name="maxLow"/]
		[/@ui.bambooSection]
	[/@ui.bambooSection]
[/@ui.bambooSection]
