[@ui.bambooSection titleKey="section.asoc"]
	[@ww.select labelKey="label.cred" name="selectedCred" required="true" list="credList"/]
	[@ww.textfield labelKey="label.appid" name="appId" required="true"/]
	[@ww.select labelKey="label.test.type" name="selectedTestType" required="true" list="testTypeList"/]
	[@ui.bambooSection dependsOn="selectedTestType" showOn="DynamicAnalyzer"]
		[@ww.textfield labelKey="label.target" name="target" required="true"/]
		[@ww.select labelKey="dyn.label.scan.type" name="ScanType" list="scanTypeList"/]
		[@ww.select labelKey="dyn.label.test.optimization" name="TestOptimizationLevel" list="testOptimizationList"/]
		[@ww.textfield labelKey="dyn.label.login.user" name="LoginUser"/]
		[@ww.password labelKey="dyn.label.login.password" name="LoginPassword" showPassword="true"/]
		[@ww.textfield labelKey="dyn.label.third.credential" name="extraField"/]
		[@ww.textfield labelKey="dyn.label.presence" name="PresenceId"/]
		[@ww.textfield labelKey="dyn.label.scan.file" name="ScanFile"/]
	[/@ui.bambooSection]
	[@ui.bambooSection dependsOn="selectedTestType" showOn="StaticAnalyzer"]
		[@ww.checkbox labelKey="label.open.source.only" name="openSourceOnly" toggle="true"/]
	[/@ui.bambooSection]
	[@ww.checkbox labelKey="label.email.notification" name="emailNotification" toggle="true"/]
	[@ww.checkbox labelKey="label.suspend" name="suspendJob" toggle="true"/]
[/@ui.bambooSection]

[@ui.bambooSection titleKey="" descriptionKey="" dependsOn="suspendJob" showOn="true"]
	[@ww.checkbox labelKey="section.fail.configure" name="failBuildConfigure" toggle="true"/]
	[@ui.bambooSection titleKey="" descriptionKey="" dependsOn="failBuildConfigure" showOn="true"]
		[@ww.radio name="selectedFailBuild" labelKey="section.fail" list="failBuildList" toggle="true"/]
		[@ui.bambooSection titleKey="" descriptionKey="section.fail.desc" dependsOn="selectedFailBuild" showOn="failBuildSeverityLevel"]
			[@ww.textfield labelKey="label.total" name="maxTotal"/]
			[@ww.textfield labelKey="label.high" name="maxHigh"/]
			[@ww.textfield labelKey="label.medium" name="maxMedium"/]
			[@ww.textfield labelKey="label.low" name="maxLow"/]
		[/@ui.bambooSection]
	[/@ui.bambooSection]
[/@ui.bambooSection]
