[@ui.bambooSection titleKey="section.asoc"]
	[@ww.label labelKey="label.cred" name="selectedCred"/]
	[@ww.label labelKey="label.appid" name="appId"/]
	[@ww.label labelKey="label.test.type" name="selectedTestType"/]
	[@ui.bambooSection dependsOn="selectedTestType" showOn="DynamicAnalyzer"]
		[@ww.label labelKey="label.target" name="target"/]
		[@ww.label labelKey="dyn.label.scan.type" name="ScanType"/]
		[@ww.label labelKey="dyn.label.test.optimization" name="TestOptimizationLevel"/]
		[@ww.label labelKey="dyn.label.login.user" name="LoginUser"/]
		[@ww.label labelKey="dyn.label.login.password" name="LoginPassword" showPassword="true"/]
		[@ww.label labelKey="dyn.label.third.credential" name="extraField"/]
		[@ww.label labelKey="dyn.label.presence" name="PresenceId"/]
		[@ww.label labelKey="dyn.label.scan.file" name="ScanFile"/]
	[/@ui.bambooSection]
	[@ui.bambooSection dependsOn="selectedTestType" showOn="StaticAnalyzer"]
		[@ww.checkbox labelKey="label.open.source.only" name="openSourceOnly" toggle="true" disabled="true"/]
		[@ww.checkbox labelKey="section.scan.speed" name="staticScanSpeedConf" toggle="true" disabled="true"/]
		[@ui.bambooSection titleKey="" descriptionKey="" dependsOn="staticScanSpeedConf" showOn="true"]
			[@ww.radio name="staticScanSpeed" labelKey="" list="staticScanSpeedList" toggle="true" disabled="true"/]
		[/@ui.bambooSection]
	[/@ui.bambooSection]
	[@ww.checkbox labelKey="label.email.notification" name="emailNotification" toggle="true" disabled="true"/]
	[@ww.checkbox labelKey="label.suspend" name="suspendJob" toggle="true" disabled="true"/]
[/@ui.bambooSection]

[@ui.bambooSection titleKey="" descriptionKey="" dependsOn="suspendJob" showOn="true"]
	[@ww.checkbox labelKey="section.fail.configure" name="failBuildConfigure" toggle="true" disabled="true"/]
	[@ui.bambooSection titleKey="" descriptionKey="" dependsOn="failBuildConfigure" showOn="true"]
		[@ww.radio name="selectedFailBuild" labelKey="section.fail" list="failBuildList" toggle="true"  disabled="true"/]
		[@ui.bambooSection titleKey="" descriptionKey="section.fail.desc" dependsOn="selectedFailBuild" showOn="failBuildSeverityLevel"]
			[@ww.label labelKey="label.total" name="maxTotal"/]
			[@ww.label labelKey="label.high" name="maxHigh"/]
			[@ww.label labelKey="label.medium" name="maxMedium"/]
			[@ww.label labelKey="label.low" name="maxLow"/]
		[/@ui.bambooSection]
	[/@ui.bambooSection]
[/@ui.bambooSection]
