[@ui.bambooSection titleKey="section.asoc"]
	[@ww.label labelKey="label.api.keyid" name="apiKey" descriptionKey="desc.api.keyId"/]
	[@ww.label labelKey="label.api.secret" name="apiSecret" descriptionKey="desc.api.secret"/]
	[@ww.label labelKey="label.appid" name="appId" descriptionKey="desc.appid"/]
	[@ww.label labelKey="label.scanName" name="scanName" descriptionKey="desc.scanName"/]
	[@ww.label labelKey="label.test.type" name="selectedTestType" descriptionKey="desc.testType"/]
	[@ui.bambooSection dependsOn="selectedTestType" showOn="DynamicAnalyzer"]
		[@ww.label labelKey="label.target" name="target" descriptionKey="desc.target"/]
		[@ww.label labelKey="dyn.label.scan.type" name="ScanType" descriptionKey="desc.dynScanType"/]
		[@ww.label labelKey="dyn.label.test.optimization" name="TestOptimizationLevel" descriptionKey="desc.dyn.testOptimization"/]
		[@ww.label labelKey="dyn.label.login.user" name="LoginUser" descriptionKey="desc.dynLoginUser"/]
		[@ww.label labelKey="dyn.label.login.password" name="LoginPassword" descriptionKey="desc.dynLoginPassword" showPassword="true"/]
		[@ww.label labelKey="dyn.label.third.credential" name="extraField" descriptionKey="dyn.thirdCred"/]
		[@ww.label labelKey="dyn.label.presence" name="PresenceId" descriptionKey="desc.dynPresence"/]
		[@ww.label labelKey="dyn.label.scan.file" name="ScanFile" descriptionKey="desc.dynScanFile"/]
	[/@ui.bambooSection]
	[@ui.bambooSection dependsOn="selectedTestType" showOn="StaticAnalyzer"]
		[@ww.checkbox labelKey="label.open.source.only" name="openSourceOnly" descriptionKey="desc.openSourceOnly" toggle="true" disabled="true"/]
		[@ww.checkbox labelKey="section.scan.speed" name="staticScanSpeedConf" descriptionKey="dec.scanSpeed" toggle="true" disabled="true"/]
		[@ui.bambooSection titleKey="" descriptionKey="" dependsOn="staticScanSpeedConf" showOn="true"]
			[@ww.radio name="staticScanSpeed" labelKey="" list="staticScanSpeedList" toggle="true" disabled="true"/]
		[/@ui.bambooSection]
	[/@ui.bambooSection]
	[@ww.checkbox labelKey="label.email.notification" name="emailNotification" descriptionKey="desc.emailNotification" toggle="true" disabled="true"/]
	[@ww.checkbox labelKey="label.suspend" name="suspendJob" descriptionKey="desc.suspend" toggle="true" disabled="true"/]
[/@ui.bambooSection]

[@ui.bambooSection titleKey="" descriptionKey="" dependsOn="suspendJob" showOn="true"]
	[@ww.checkbox labelKey="section.fail.configure" name="failBuildConfigure" descriptionKey="desc.failConfigure" toggle="true" disabled="true"/]
	[@ui.bambooSection titleKey="" descriptionKey="" dependsOn="failBuildConfigure" showOn="true"]
		[@ww.radio name="selectedFailBuild" labelKey="section.fail" list="failBuildList" toggle="true"  disabled="true"/]
		[@ui.bambooSection titleKey="" descriptionKey="desc.section.fail" dependsOn="selectedFailBuild" showOn="failBuildSeverityLevel"]
			[@ww.label labelKey="label.total" name="maxTotal"/]
			[@ww.label labelKey="label.high" name="maxHigh"/]
			[@ww.label labelKey="label.medium" name="maxMedium"/]
			[@ww.label labelKey="label.low" name="maxLow"/]
		[/@ui.bambooSection]
	[/@ui.bambooSection]
[/@ui.bambooSection]
